// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeMJQwFP5mb5-QlN4TKE1dJG7OaFsYGGU',
    appId: '1:313556152728:web:295d0b9500eacd457fbbed',
    messagingSenderId: '313556152728',
    projectId: 'real-time-signal-checker',
    authDomain: 'real-time-signal-checker.firebaseapp.com',
    storageBucket: 'real-time-signal-checker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI4hQSSq-26V31gHKpQYH_kzSdK2Jt0CU',
    appId: '1:313556152728:android:62a2f7b4d87b1b7d7fbbed',
    messagingSenderId: '313556152728',
    projectId: 'real-time-signal-checker',
    storageBucket: 'real-time-signal-checker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkxjTV9RMERY6udoIZbbDvO0Ry8Rj1_OI',
    appId: '1:313556152728:ios:3b6680e28603ec9b7fbbed',
    messagingSenderId: '313556152728',
    projectId: 'real-time-signal-checker',
    storageBucket: 'real-time-signal-checker.appspot.com',
    iosBundleId: 'com.example.realTimeSignalStrengthChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkxjTV9RMERY6udoIZbbDvO0Ry8Rj1_OI',
    appId: '1:313556152728:ios:298db78d08a595b97fbbed',
    messagingSenderId: '313556152728',
    projectId: 'real-time-signal-checker',
    storageBucket: 'real-time-signal-checker.appspot.com',
    iosBundleId: 'com.example.realTimeSignalStrengthChecker.RunnerTests',
  );
}
